version: '3.8'

services:
  backend:
    build:
      context: ./spring-stomp-practice-back
      dockerfile: Dockerfile
    container_name: chat-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - chat-network

  frontend:
    build:
      context: ./spring-stomp-practice-front
      dockerfile: Dockerfile
    container_name: chat-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - chat-network
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8080

networks:
  chat-network:
    driver: bridge 